### ISSUE TITLE
Object Storage: Clarify "three times redundancy"

### ISSUE THREAD

**Issue by kescherCode** [contabo/docs#14]
At the technical description of the Object Storage product, it is stated that https://github.com/contabo/docs/blob/1c98650c33250731eba1df6c2cac97498471e741/docs/products/Object-Storage/technical-description.md?plain=1#L26

However, it is unclear what this means. I'm currently assuming something some RAID level is supposed to be here.
If this is the case, it should be changed to say: "**All** data stored is stored on a RAID \<RAID level> array".

**Comment by reoops** [comment]
No, there is no RAID. Data redundancy is handled by Ceph itself. 3 times redundancy means simply that you can loose up to 3 parts out of 4 parts without loosing the data. Parts might be either disks or nodes.

**Comment by reoops** [comment]
Closed due to inactivity.
