### ISSUE TITLE
Restricting Users to Buckets: Whitelist approach possible?

### ISSUE THREAD

**Issue by thurse93** [contabo/docs#15]
I refer to: https://github.com/contabo/docs/blob/15f5fabfbaff2fe5375b96f465dbc999c0ef7814/docs/products/Object-Storage/HowTo/restricting-user-bucket.md

If I understand it correctly, this example shows how to mutually exclude user-1/2 from bucket-1/2. However in a more real-world scenario one would prefer to deny access to ALL users except a selected list per-bucket, effectively creating a whitelist for every bucket. Is this possible with Ceph / S3 Bucket Policies?

**Comment by reoops** [comment]
Yes, you should be able to do that. Please refer to https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-policies.html and https://docs.ceph.com/en/quincy/radosgw/bucketpolicy/.

**Comment by reoops** [comment]
Closed due to inactivity.
