### ISSUE TITLE
Terrible documentation

### ISSUE THREAD

**Issue by kamalkech** [contabo/docs#26]
i guess the documentation need a documentation too

for example here https://docs.contabo.com/docs/products/Object-Storage/HowTo/public-sharing

Create a file public-sharing-policy.json with following content, where we can create a file ....etc
should make i clean / clear documentation to understand the api

**Comment by reoops** [comment]
The API itself is documented at <https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-policies.html>. The mentioned page contains some examples in form of an how to.

Do you think we should point that out more?
